unstable_features          = true
edition                    = "2018"
error_on_unformatted       = true
error_on_line_overflow     = true
condense_wildcard_suffixes = true
comment_width              = 80
format_strings             = true
format_macro_matchers      = true
imports_indent             = "Visual"
merge_imports              = true
match_block_trailing_comma = true
normalize_comments         = true
reorder_impl_items         = true
report_todo                = "Unnumbered"
report_fixme               = "Unnumbered"
use_field_init_shorthand   = true
use_try_shorthand          = true
wrap_comments              = true
